# Generated by Django 4.0.6 on 2022-08-07 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinemeet', '0002_meeting_ending_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='duration',
            field=models.PositiveIntegerField(default=45),
            preserve_default=False,
        ),
    ]
